<!-- Company / Institiute Name -->
<div class="field company_name">
  <label class="label" for="company_name">
    <span><?= $block->escapeHtml(__('Company / Institiute Name')) ?></span>
  </label>
  <div class="control">
    <input type="text" name="company_name" id="company_name" value="" title="<?= $block->escapeHtmlAttr(__('Company / Institiute Name')) ?>" class="input-text">
  </div>
</div>

<!-- Designation -->
<div class="field common_block">
  <div class="field contact_number">
    <label class="label" for="designation">
      <span><?= $block->escapeHtml(__('Designation')) ?></span>
    </label>
    <div class="control">
      <input type="text" name="designation" id="designation" value="" title="<?= $block->escapeHtmlAttr(__('Designation')) ?>" class="input-text">
    </div>
  </div>

  <!-- GST/VAT No -->
  <div class="field gst_number">
    <label class="label" for="gst_number">
      <span><?= $block->escapeHtml(__('GST/VAT No')) ?></span>
    </label>
    <div class="control">
      <input type="text" name="gst_number" id="gst_number" value="" title="<?= $block->escapeHtmlAttr(__('GST/VAT No')) ?>" class="input-text" maxlength="15">
      <div style="color:#e02b27;margin-top:5px"><label id="gst_valid"></label></div>
    </div>
  </div>
</div>

<!-- Contact Number -->
<div class="field contact_number">
  <label class="label" for="contact_number">
    <span><?= $block->escapeHtml(__('Contact Number')) ?></span>
  </label>
  <div class="control">
    <input type="text" name="contact_number" id="contact_number" value="" title="<?= $block->escapeHtmlAttr(__('Contact Number')) ?>" class="input-text" minlength="7" maxlength="15">
  </div>
</div>

<!-- Country -->
<div class="field common_block">
  <div class="field countryid required">
      <label class="label" for="countryid">
        <span><?= $block->escapeHtml(__('Country')) ?></span>
      </label>
    <div class="control select_block">
      <field name="countryid" formElement="select">   
          <formElements>
            <?= $block->getCountries();?>
          </formElements>
      </field>
    </div>
  </div>

  <!-- State/Province -->
  <div class="field stateid required">
      <label class="label" for="stateid">
        <span><?= $block->escapeHtml(__('State/Province')) ?></span>
      </label>
    <div class="control select_block">
      <field name="stateid" formElement="select">   
          <formElements>
            <?= $block->getRegion();?>
          </formElements>
      </field>
      <input required type='text' id='custom_state' name='custom_state' style="display:none">
      <input type="hidden" id="is_custom_state" name="is_custom_state">
    </div>
  </div>
</div>

<!-- Interested Area -->
<div class="field interested_area">
  <label class="label" for="interested_area">
    <span><?= $block->escapeHtml(__('Interested Area')) ?><span class="select_item"><?= $block->escapeHtml(__('(Select atleast 1 item)')) ?></span></span>
  </label>    
  <div class="control">
    <select id="interested_area" name="interested_area[]" multiple="multiple">
      <option value="microbiology">Microbiology</option>
      <option value="cell_biology">Cell Biology</option>
      <option value="molecular_biology">Molecular Biology</option>
      <option value="hydroponics_soilless_farming">Hydroponics soilless farming</option>
      <option value="plant_tissue_culture">Plant Tissue culture</option>
      <option value="chemicals">Chemicals & Biochemicals</option>
      <option value="lab_consumables">Lab Consumables & Instruments</option>
    </select>
    <div style="color:#e02b27;margin-top:5px"><label id="interested_area_error"></label></div>
  </div>
</div>

<!-- Sign Up for Newsletter -->
<div class="field choice newsletter">
    <input type="checkbox"
            name="is_subscribed"
            title="<?= $escaper->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>"
            value="1"
            id="is_subscribed"
            class="checkbox">
    <label for="is_subscribed" class="label">
        <span><?= $escaper->escapeHtml(__('Sign Up for Newsletter')) ?></span>
    </label>
</div>

<!-- Agree to Terms & Conditions -->
<div class="field is_agreed">    
  <div class="control">
      <input type="checkbox" name="is_agreed" id="is_agreed" class="checkbox" value="1" required> 
      <div><label for="is_agreed" class="label">I agree to the <a href="#" id="lblTerms" download>Terms & Conditions <img src="<?php echo $this->getViewFileUrl('images/registration_icon.png'); ?>" alt="User"></a> </label></div>
  </div>
</div>

<script>
  require(['jquery', 'mage/multiselect'], function($){
    var path = window.location.protocol+'//'+window.location.host;
    var pdfPath = path+'/media/terms/pdf/default/terms-of-use.pdf';
    $("#lblTerms").prop("href", pdfPath);
    //State is empty initially
    $("#state").empty();
    $(document).on('change','#country',function() {
      var param = 'country='+$('#country').val();
      $.ajax({
          showLoader: true,
          url: '<?php /* @escapeNotVerified */ echo $block->getCountryAction(); ?>',
          data: param,
          type: "GET",
          dataType: 'json'
      }).done(function (data) {
          $('#state').empty();
          $("#country").attr("name","countryid");
          $("#state").attr("name","stateid");
          //data.value has the array of regions
          if(data.value.length == 0) {
            $("#is_custom_state").val("1");
            $("#custom_state").show().val('');
            $("#state, #state-error").hide();
          } else {
            $("#is_custom_state").val("0");
            $("#custom_state, #custom_state-error").hide();
            $("#state").show();
          }
          $(data.value).each(function()
          {
            var option = $('<option />');
            option.attr('value', this.region_id).text(this.name);
            $('#state').append(option);
          });
      });
    });

    $("#telephone").attr({'minlength':'7', 'maxlength':'15'});

    $(document).on('keypress','#contact_number, #telephone',function(evt) {
      evt = (evt) ? evt : window.event;
      var charCode = (evt.which) ? evt.which : evt.keyCode;
      if (charCode > 31 && (charCode < 48 || charCode > 57)) {
          return false;
      }
      return true;
    });

    $(document).on('keypress','#gst_number',function(e) {
      var code = ('charCode' in e) ? e.charCode : e.keyCode;
      if (
        !(code == 13) && // enter
        !(code > 47 && code < 58) && // numeric (0-9)
        !(code > 64 && code < 91) && // upper alpha (A-Z)
        !(code > 96 && code < 123)) { // lower alpha (a-z)
        e.preventDefault();
      }
    });

    $(document).on('keypress','#custom_state',function(e) {
      var code = ('charCode' in e) ? e.charCode : e.keyCode;
      if (
        !(code == 13) && // enter
        !(code == 32) && // space
        !(code > 64 && code < 91) && // upper alpha (A-Z)
        !(code > 96 && code < 123)) { // lower alpha (a-z)
        e.preventDefault();
      }
    });
   
    $(document).on('click','.action',function(e) {
      $("#form-validate").valid();
      gstvalidation();
      var error_count = 0;
      if($("#custom_state").val().trim().length == 0 && $("#is_custom_state").val() == "1") {
        $("#custom_state-error").remove();
        $('<div id="custom_state-error" class="mage-error">This is a required field.</div>').insertAfter("#custom_state");
        $("#custom_state").focus();
        error_count++;
      }
      if($("#interested_area").val().length == 0) {
        $("#interested_area_error").html('<label id="interested_area_error">This is a required field.</label>')
        error_count++;
      } else {
        $("#interested_area_error").html('');
      }

      if(error_count > 0) {
        return false;
      }
    });
    
});

function gstvalidation() {
  var gstno = jQuery('#gst_number').val();
  var reggst = /^([0-9]){2}([A-Z a-z]){5}([0-9]){4}([A-Z a-z]){1}([0-9]){1}([A-Z a-z]){1}([A-Z a-z 0-9]){1}?$/;
  if(!reggst.test(gstno) && gstno!='') { 
    jQuery('#gst_valid').html('GST No. is not valid It should be in this "11AAAAA1111Z1A1" format').css({"color": 'e02b27'}).focus();
    jQuery('#gst_valid').focus();
    return false;
  } else {
    jQuery('#gst_valid').html('');      
    return true;          
  }
}

require([
  'jquery',
  'jquery/ui',
  'Vendorname_Customer/js/jquery.multi-select'
  ],
  function($, modal) {
    $(document).ready( function() {
      $('#interested_area').multiSelect();
  });
});

</script> 